### ISSUE TITLE
Error "error: Uncaught SyntaxError: The requested module 'https://deno.land/std/io/mod.ts' does not provide an export named " after building tg file

### ISSUE THREAD

**Issue by csallen1204** [Twingate-Labs/tg-cli#7] opened 2022-10-21 15:32 UTC
Trying to build tg on Ubuntu 20.04 using latest version of deno. Build completed but I get this error when trying to use command:

```
ascii@thinkpad-x1:~/git-repo/tg-cli$ ./tg --help
error: Uncaught SyntaxError: The requested module 'https://deno.land/std/io/mod.ts' does not provide an export named 'readerFromStreamReader'
import { readerFromStreamReader } from "https://deno.land/std/io/mod.ts";
         ^
    at <anonymous> (file:///home/ascii/git-repo/tg-cli/utils/smallUtilFuncs.mjs:294:10)
```

**Comment by chenbishop** [comment] 2022-10-21 16:27
Hi @csallen1204 

I suspect the issue is caused by the command used for compiling is not correct. 

If you are compiling in linux please use the following command


deno cache --reload ./tg.js --unstable
deno bundle --unstable --import-map ./import_map.json ./tg.js ./tg.bundle.js
deno compile --allow-all --unstable --target x86_64-unknown-linux-gnu --output ./tg ./tg.bundle.js &



Please let me know if this works.

**Comment by csallen1204** [comment] 2022-10-21 16:49
That got me past that error but got me to a new one: 

```
ascii@thinkpad-x1:~/git-repo/tg-cli$ ./tg export
 ? Enter Twingate account: › [ERROR]   Exception: TypeError: Deno.setRaw is not a function
    at Input.#readChar (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:6179:18)
    at Input.#readKey (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:6172:42)
    at Input.read (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:6121:47)
    at Input.#execute (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:6072:25)
    at async Input.prompt (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:6058:20)
    at async PromptList.runPrompt (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:7380:45)
    at async file:///home/ascii/git-repo/tg-cli/tg.bundle.js:7312:17
    at async PromptList.runBeforeHook (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:7368:9)
    at async PromptList.next (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:7310:13)
    at async PromptList.run (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:7305:9)
```

I tested both the master and development branches and got the same thing.

**Comment by chenbishop** [comment] 2022-10-21 16:51
this has just been fixed (1 hour ago), could you pull the latest code and try again please?

**Comment by csallen1204** [comment] 2022-10-21 16:53
Same error: 

```
ascii@thinkpad-x1:~/git-repo/tg-cli$ git pull
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 6 (delta 3), reused 6 (delta 3), pack-reused 0
Unpacking objects: 100% (6/6), 913 bytes | 76.00 KiB/s, done.
From https://github.com/Twingate-Labs/tg-cli
   4061309..d7c8611  main       -> origin/main
 * [new tag]         v0.0.56    -> v0.0.56
 * [new tag]         v0.0.55    -> v0.0.55
Updating 4061309..d7c8611
Fast-forward
 TwingateApiClient.mjs | 2 +-
 import_map.json       | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)
ascii@thinkpad-x1:~/git-repo/tg-cli$ deno compile --allow-all --unstable --target x86_64-unknown-linux-gnu --output ./tg ./tg.bundle.js &
[1] 28930
ascii@thinkpad-x1:~/git-repo/tg-cli$ Compile file:///home/ascii/git-repo/tg-cli/tg.bundle.js
Archive:  /tmp/.tmpushH0o/deno.zip
  inflating: deno                    
Emit ./tg

[1]+  Done                    deno compile --allow-all --unstable --target x86_64-unknown-linux-gnu --output ./tg ./tg.bundle.js
ascii@thinkpad-x1:~/git-repo/tg-cli$ ./tg export
 ? Enter Twingate account: › [ERROR]   Exception: TypeError: Deno.setRaw is not a function
    at Input.#readChar (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:6179:18)
    at Input.#readKey (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:6172:42)
    at Input.read (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:6121:47)
    at Input.#execute (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:6072:25)
    at async Input.prompt (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:6058:20)
    at async PromptList.runPrompt (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:7380:45)
    at async file:///home/ascii/git-repo/tg-cli/tg.bundle.js:7312:17
    at async PromptList.runBeforeHook (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:7368:9)
    at async PromptList.next (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:7310:13)
    at async PromptList.run (file:///home/ascii/git-repo/tg-cli/tg.bundle.js:7305:9)
ascii@thinkpad-x1:~/git-repo/tg-cli$ 
```

**Comment by chenbishop** [comment] 2022-10-21 16:56
I suspect this is caused by the packages from import map is cached.

could you run all of the following commands

deno cache --reload ./tg.js --unstable
deno bundle --unstable --import-map ./import_map.json ./tg.js ./tg.bundle.js
deno compile --allow-all --unstable --target x86_64-unknown-linux-gnu --output ./tg ./tg.bundle.js &

**Comment by csallen1204** [comment] 2022-10-21 16:58
It's working! Thanks!

**Comment by chenbishop** [comment] 2022-10-21 17:28
Thats great! 

Closing the issue.

**Closed by chenbishop** 2022-10-21 17:28 UTC
